version: "3.2"

services:
  neo:
    build: neo4j
    ports:
      - "5007:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/entrypoint:/var/lib/neo4j/entrypoint
    environment:
      NEO4J_USERNAME: $NEO4J_USER
      NEO4J_PASSWORD: $NEO4J_PW
      NEO4J_AUTH: $NEO4J_USER/$NEO4J_PW
      DB_HOST: $DB_HOST
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PW: $DB_PW

networks:
  default:
    external:
      name: dbas_default