version: "3.2"

services:
  neo:
    build: .
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/entrypoint:/var/lib/neo4j/entrypoint
    env_file:
      - .env
networks:
  default:
    external:
      name: dbas_default