version: "3.2"

services:
  neo:
    build: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      - ./neo4j/entrypoint:/var/lib/neo4j/entrypoint
    environment:
      NEO4J_USERNAME: $NEO4J_USER
      NEO4J_PASSWORD: $NEO4J_PW
      NEO4J_AUTH: $NEO4J_USER/$NEO4J_PW
      NEO4J_dbms_security_procedures_unrestricted: algo.*, apoc.*

networks:
  default:
    external:
      name: dbas_default