version: "3.2"

services:
  neo:
    image: gitlab.cs.uni-duesseldorf.de:5001/cn-tsn/project/dbas/neodb
    ports:
      - "5007:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/entrypoint:/var/lib/neo4j/entrypoint
    env_file:
      - .production.env
networks:
  default:
    external:
      name: dbas_default